import {cn} from "@corensystem/core-utils";
import {Box, Boxes, Home, Layers, LayoutGrid, Map as MapIcon, X} from "lucide-react";
// DRAFT template — generated by wakedex from Mobbin flow "1 pasted screenshot(s)"
// (run mtt38uye-capture-ui-enhanced, Core develop@d1ef538). The flow's screens are
// composed into one navigable page (in-page screen switching, mock data), built
// from the reviewed component variants. Review + add a manifest before promoting.
import {useEffect, useLayoutEffect, useMemo, useRef, useState} from "react";

import {Badge} from "../badge";
import {BuildingViewer} from "../building-viewer";
import {Button} from "../button";
import {type CanvasNavigatorNode} from "../canvas-navigator";
import {Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle} from "../dialog";
// The reality viewer pulls in @thatopen + three (heavy WebGL/3D deps). Import it lazily so consumers
// that only render the 2D dashboard never have to bundle or install those peers — the module is fetched
// on demand the first time the 3D view mounts (see RealityMeshCanvas). 3D-only consumers still resolve it.
import type {FootprintViewer} from "../footprint-viewer";
import {useMapTransition} from "../map-transition";
import {ProgressSheet} from "../progress-sheet";
import {
	approvedProgressToBucket,
	classifyVariance,
	type MapMode,
	PROGRESS_LEGEND_ITEMS,
	VARIANCE_LEGEND_ITEMS,
	type Villa as SiteVilla,
} from "../site-image-viewer";
import {
	ALMANAR_BATCHES,
	ALMANAR_PHASE_META,
	ALMANAR_PHASES,
	ALMANAR_SITE_META,
	ALMANAR_VILLAS,
	ALMANAR_ZONE_A_BLOCKS,
	ALMANAR_ZONE_B_BLOCKS,
	ALMANAR_ZONE_B_META,
	ALMANAR_ZONE_B_VILLAS,
	ALMANAR_ZONE_MARKETING_META,
	ALMANAR_ZONE_META,
	ALMANAR_ZONES,
	ALMANAR_ZONES_MARKETING,
} from "../site-image-viewer-fixtures";
import {type CaptureFilter, type CaptureFilterOptions, SitePanel} from "../site-panel";
import {SiteToolbar} from "../site-toolbar";
import {ALMANAR_VILLA_BLOCK} from "./almanar-blocks-data";
import {ALMANAR_HIERARCHY} from "./almanar-hierarchy-data";
import {
	ALMANAR_BATCHES_BY_ZONE,
	ALMANAR_BLOCKS_BY_ZONE,
	ALMANAR_VILLA_BATCH,
	ALMANAR_VILLA_BLOCK_NAME,
} from "./almanar-villa-taxonomy";
import {DRONE_THUMB, PLAN_THUMB} from "./view-mode-thumbs";

/* ------------------------------------------------------------------ *
 * Mock data
 * ------------------------------------------------------------------ */

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const fmtDate = (d: Date) => `${MONTHS[d.getMonth()]} ${d.getDate()}, ${d.getFullYear()}`;

interface TimelineWeek {
	value: string;
	/** Week number shown on the tick (unless it starts a month). */
	num: number;
	start: Date;
	end: Date;
	/** True when this week begins a new month — the tick shows the month name instead of the number. */
	monthStart: boolean;
	monthLabel: string;
}

/**
 * Weekly reality-capture runs — one tick per week. Week 122 is the current Sep 5–11, 2026 window. Dates
 * are generated from that anchor so month boundaries (the first week that starts a new month) can be
 * flagged; those ticks render the month name in place of the week number.
 */
const TIMELINE_WEEKS_DEFAULT: TimelineWeek[] = (() => {
	const anchor = new Date(2026, 8, 5); // week 122 start (Sep 5, 2026)
	const anchorNum = 122;
	const DAY = 86_400_000;
	const raw = [] as {value: string; num: number; start: Date; end: Date}[];
	// The timeline ends at next week (anchor + 1); this week (122) is the default selection.
	for (let n = 88; n <= anchorNum + 1; n++) {
		const start = new Date(anchor.getTime() + (n - anchorNum) * 7 * DAY);
		raw.push({value: String(n), num: n, start, end: new Date(start.getTime() + 6 * DAY)});
	}
	return raw.map((w, i) => ({
		...w,
		monthStart: i > 0 && w.start.getMonth() !== raw[i - 1].start.getMonth(),
		monthLabel: MONTHS[w.start.getMonth()],
	}));
})();

type Villa = {
	/** Stable unique id (the fixture villa id as a string). */
	id: string;
	/** Display name, e.g. "2279 VL6-L". */
	name: string;
	meta: string;
	/** Approved progress, 0–100. */
	approved: number;
	/** Planned progress, 0–100. */
	planned: number;
};

/** Map a villa name's type code to a human label (e.g. "2279 VL6-L" → "Villa"). */
const VILLA_TYPE_LABELS: Record<string, string> = {
	TH: "Townhouse",
	DT: "Detached",
	VL: "Villa",
	VD: "Villa Duplex",
	DP: "Duplex",
};

function villaTypeLabel(name: string) {
	const code = name.match(/[A-Z]{2}/)?.[0];
	return (code && VILLA_TYPE_LABELS[code]) || "Unit";
}

/** Map SiteImageViewer villa footprints to the left-rail row shape, so the list matches what's drawn. */
function villaRows(villas: SiteVilla[]): Villa[] {
	return villas.map((v) => ({
		id: String(v.id),
		name: v.name,
		meta: `${villaTypeLabel(v.name)} · Plot ${v.plotNumber}`,
		approved: Math.round(v.approvedProgressPercent ?? 0),
		planned: Math.round(v.plannedProgressPercent ?? 0),
	}));
}

/** Zone 1-A's 301 villas over the drone aerial (the default villa view). */
const VILLAS: Villa[] = villaRows(ALMANAR_VILLAS);

/**
 * Per-zone villa overlays — the current-location stepper switches which zone's villas the villa view draws.
 * Each zone has its own blueprint image + footprints (Zone 1-A: 301 over the aerial; Zone 1-B: 432 over its
 * own villa blueprint). Zones without pulled data fall back to Zone 1-A.
 */
/** One drill-down location's villa overlay: the polygons, the list rows, and the backing blueprint image. */
export type ZoneVillaView = {
	villas: SiteVilla[];
	rows: Villa[];
	backgroundUrl: string;
	imageWidth: number;
	imageHeight: number;
};

/**
 * A blank view used when a host supplies a data prop but has no entry for the requested key. Renders no
 * polygons and a neutral (empty) background/label — never bundled fixture content.
 */
const EMPTY_VIEW: ZoneVillaView = {
	villas: [],
	rows: [],
	backgroundUrl: "",
	imageWidth: 0,
	imageHeight: 0,
};

const ZONE_VILLA_VIEWS_DEFAULT: Record<string, ZoneVillaView> = {
	"zone-1-a": {
		villas: ALMANAR_VILLAS,
		rows: VILLAS,
		backgroundUrl: "/site-background.webp",
		imageWidth: ALMANAR_SITE_META.imageWidth,
		imageHeight: ALMANAR_SITE_META.imageHeight,
	},
	"zone-1-b": {
		villas: ALMANAR_ZONE_B_VILLAS,
		rows: villaRows(ALMANAR_ZONE_B_VILLAS),
		backgroundUrl: "/zone1b-villa-blueprint.webp",
		imageWidth: ALMANAR_ZONE_B_META.imageWidth,
		imageHeight: ALMANAR_ZONE_B_META.imageHeight,
	},
};

/** Every villa across both zones (301 + 432 = 733) — the Reports grid draws one coloured block per villa. */
const ALL_VILLAS_DEFAULT: SiteVilla[] = [...ALMANAR_VILLAS, ...ALMANAR_ZONE_B_VILLAS];

/** Map a level's polygons to the left-rail row shape. */
function toRows(polys: SiteVilla[]): Villa[] {
	return polys.map((b) => ({
		id: String(b.linkedLbsItemId ?? b.id),
		name: b.name,
		meta: b.plotNumber ? `${b.plotNumber} units` : "",
		approved: Math.round(b.approvedProgressPercent ?? 0),
		planned: Math.round(b.plannedProgressPercent ?? 0),
	}));
}

/**
 * The parent LBS levels for the "Batch" slot. Each level draws its own polygons over its own Capture
 * blueprint image (Batch reuses the villa aerial; Zone/Phase have their own images at their own sizes).
 * `block` is NOT here — it's location-aware (per zone), resolved from BLOCK_VIEWS_DEFAULT below.
 */
const LEVEL_VIEW_DEFAULT: Partial<Record<LevelId, ZoneVillaView>> = {
	batch: {
		villas: ALMANAR_BATCHES,
		rows: toRows(ALMANAR_BATCHES),
		backgroundUrl: "/site-background.webp",
		imageWidth: ALMANAR_SITE_META.imageWidth,
		imageHeight: ALMANAR_SITE_META.imageHeight,
	},
	// Zone (under the Batch dropdown) shows the marketing render — the "originally wanted" zone basemap.
	// Zone (under the Batch dropdown) uses the marketing render — the "originally wanted" zone basemap.
	zone: {
		villas: ALMANAR_ZONES_MARKETING,
		rows: toRows(ALMANAR_ZONES_MARKETING),
		backgroundUrl: "/zone-marketing-blueprint.webp",
		imageWidth: ALMANAR_ZONE_MARKETING_META.imageWidth,
		imageHeight: ALMANAR_ZONE_MARKETING_META.imageHeight,
	},
	phase: {
		villas: ALMANAR_PHASES,
		rows: toRows(ALMANAR_PHASES),
		backgroundUrl: "/phase-blueprint.webp",
		imageWidth: ALMANAR_PHASE_META.imageWidth,
		imageHeight: ALMANAR_PHASE_META.imageHeight,
	},
};

/**
 * Block level — the ROSHN Batch → BLOCK grouping, ONE hull polygon per block. The block hulls are authored in
 * the SAME 4096×4096 pixel space as each zone's villa footprints (the marketing render, blueprint 6363/6364),
 * so the block level reuses the EXACT SAME background image as that zone's villa view (`site-background.webp`
 * for Zone 1-A, `zone1b-villa-blueprint.webp` for Zone 1-B). Same URL + dims ⇒ switching villa/batch ↔ block
 * only swaps the polygons, never reloads the image. Location-aware: the stepper picks which zone's blocks show.
 */
const BLOCK_VIEWS_DEFAULT: Record<string, ZoneVillaView> = {
	"zone-1-a": {
		villas: ALMANAR_ZONE_A_BLOCKS,
		rows: toRows(ALMANAR_ZONE_A_BLOCKS),
		backgroundUrl: ZONE_VILLA_VIEWS_DEFAULT["zone-1-a"].backgroundUrl,
		imageWidth: ZONE_VILLA_VIEWS_DEFAULT["zone-1-a"].imageWidth,
		imageHeight: ZONE_VILLA_VIEWS_DEFAULT["zone-1-a"].imageHeight,
	},
	"zone-1-b": {
		villas: ALMANAR_ZONE_B_BLOCKS,
		rows: toRows(ALMANAR_ZONE_B_BLOCKS),
		backgroundUrl: ZONE_VILLA_VIEWS_DEFAULT["zone-1-b"].backgroundUrl,
		imageWidth: ZONE_VILLA_VIEWS_DEFAULT["zone-1-b"].imageWidth,
		imageHeight: ZONE_VILLA_VIEWS_DEFAULT["zone-1-b"].imageHeight,
	},
};

/**
 * Satellite basemaps — the "Satellite" toolbar button is a toggle that swaps the *currently selected*
 * context to its satellite background: the Villa view → a clean whole-area satellite (satellite tiles +
 * site ortho, no polygons); the Zone level → the zone's satellite blueprint (the same two zone polygons
 * as the marketing render, over the aerial). Levels without a satellite blueprint (Batch/Phase) and the
 * Drone view have none, so the toggle is disabled there. Toggling only swaps the canvas basemap; the left
 * rail keeps following the selected view/level.
 */
interface SatelliteBasemap {
	backgroundUrl: string;
	villas: SiteVilla[];
	imageWidth: number;
	imageHeight: number;
}
const VILLA_SATELLITE_DEFAULT: SatelliteBasemap = {
	backgroundUrl: "/villa-satellite-blueprint.webp",
	villas: [],
	imageWidth: 895,
	imageHeight: 756,
};
const ZONE_SATELLITE_DEFAULT: SatelliteBasemap = {
	backgroundUrl: "/zone-blueprint.webp",
	villas: ALMANAR_ZONES,
	imageWidth: ALMANAR_ZONE_META.imageWidth,
	imageHeight: ALMANAR_ZONE_META.imageHeight,
};

/**
 * Distribution over the SiteImageViewer's ramps — the same buckets, labels, and colours the map polygons
 * + legend use, with each bucket's real count for the given rows. SPA = milestone ramp (M35…M100 by
 * approved %), Construction = variance (behind / on-track / ahead of plan). Works for either level.
 */
function distributionFor(rows: Villa[], mode: MapMode) {
	if (mode === "variance") {
		return VARIANCE_LEGEND_ITEMS.filter((item) => ["behind", "onTrack", "ahead"].includes(item.id)).map((b) => ({
			id: b.id,
			label: b.label,
			range: b.description,
			color: b.color,
			count: rows.filter((v) => classifyVariance(v.approved, v.planned) === b.id).length,
		}));
	}
	return PROGRESS_LEGEND_ITEMS.filter((item) => item.id.startsWith("ms")).map((b) => ({
		id: b.id,
		label: b.label,
		range: b.description,
		color: b.color,
		count: rows.filter((v) => approvedProgressToBucket(v.approved) === b.id).length,
	}));
}

type FloorStatus = "ahead" | "on-track" | "behind";

const FLOORS: {code: string; value: number; status: FloorStatus}[] = [
	{code: "RF", value: 76, status: "ahead"},
	{code: "UF", value: 22, status: "behind"},
	{code: "FF", value: 54, status: "on-track"},
	{code: "GF", value: 39, status: "behind"},
	{code: "SS", value: 94, status: "ahead"},
];

/** The zones under Phase 1 — the current-location stepper cycles between them (prev/next arrows). Each has
 *  its own villa overlay (see `ZONE_VILLA_VIEWS`). */
const LOCATIONS: {id: string; label: string}[] = [
	{id: "zone-1-a", label: "Zone 1 – A"},
	{id: "zone-1-b", label: "Zone 1 – B"},
];

/**
 * The site tree for the CanvasNavigator — the real Al Manar hierarchy from `almanar-hierarchy-data`:
 * Phase 1 (the header) → Zone → Batch → Villa (blocks + construction systems collapsed away). Villa leaves
 * resolve to their app row id so selecting one opens that villa; `NAV_VILLA_ZONE` records each leaf's zone.
 */
const rowByNumber = (villas: SiteVilla[]) => {
	const m = new Map<string, SiteVilla>();
	for (const v of villas) {
		const n = v.name.match(/^\d+/)?.[0];
		if (n && !m.has(n)) m.set(n, v);
	}
	return m;
};
const ROW_BY_NUMBER: Record<string, Map<string, SiteVilla>> = {
	"zone-1-a": rowByNumber(ALMANAR_VILLAS),
	"zone-1-b": rowByNumber(ALMANAR_ZONE_B_VILLAS),
};
/** Villa row id → its zone, so the navigator's onSelect can switch to the right zone before opening it. */
const NAV_VILLA_ZONE_DEFAULT = new Map<string, string>();
// Group a batch's villas by their block (ROSHN nests Zone → Batch → BLOCK → Villa). Villas with no captured
// block record fall into a trailing "Unassigned" group so none are dropped. Blocks sort numerically.
function blockNodesForBatch(loc: string, batchName: string, villaNumbers: string[]): CanvasNavigatorNode[] {
	const groups = new Map<string, {block: string; villas: CanvasNavigatorNode[]}>();
	const order: string[] = [];
	for (const num of villaNumbers) {
		const v = ROW_BY_NUMBER[loc]?.get(num);
		if (!v) continue;
		const id = String(v.id);
		NAV_VILLA_ZONE_DEFAULT.set(id, loc);
		const block = ALMANAR_VILLA_BLOCK[num] ?? "";
		const key = block || "unassigned";
		let group = groups.get(key);
		if (!group) {
			group = {block, villas: []};
			groups.set(key, group);
			order.push(key);
		}
		group.villas.push({id, label: v.name, icon: <Home className="wwc:size-4" />});
	}
	order.sort((a, b) => {
		if (a === "unassigned") return 1;
		if (b === "unassigned") return -1;
		return Number(a) - Number(b);
	});
	return order.map((key) => {
		const group = groups.get(key) ?? {block: "", villas: []};
		return {
			id: `block::${loc}::${batchName}::${key}`,
			label: group.block ? `Block ${group.block}` : "Unassigned",
			icon: <Boxes className="wwc:size-4" />,
			children: group.villas,
		};
	});
}
const NAV_NODES_DEFAULT: CanvasNavigatorNode[] = LOCATIONS.map((loc) => ({
	id: loc.id,
	label: loc.label,
	icon: <MapIcon className="wwc:size-4" />,
	children: (ALMANAR_HIERARCHY[loc.id] ?? []).map((batch) => ({
		id: `batch::${loc.id}::${batch.name}`,
		label: batch.units ? `${batch.name} · ${batch.units} units` : batch.name,
		icon: <LayoutGrid className="wwc:size-4" />,
		children: blockNodesForBatch(loc.id, batch.name, batch.villaNumbers),
	})),
}));

/**
 * Map a zone polygon's `id` → its `ZONE_VILLA_VIEWS` location, so clicking a zone on the map drills into the
 * matching zone's villas (not always Zone 1-A). Built from every zone-level dataset (marketing + satellite),
 * keyed on the same id the rows use; the trailing "A"/"B" of the name picks the location.
 */
const ZONE_LOCATION_BY_ID: Record<string, string> = {};
for (const z of [...ALMANAR_ZONES_MARKETING, ...ALMANAR_ZONES]) {
	const last = z.name.trim().slice(-1).toLowerCase();
	const loc = last === "a" ? "zone-1-a" : last === "b" ? "zone-1-b" : null;
	if (loc) ZONE_LOCATION_BY_ID[String(z.linkedLbsItemId ?? z.id)] = loc;
}

/* ------------------------------------------------------------------ *
 * Helpers
 * ------------------------------------------------------------------ */

/** The LBS level shown on the canvas — Villa (leaf) or Batch (parent grouping, with the level dropdown). */
type ViewId = "villa" | "batch";
/** How the canvas is rendered, independent of the level: 2D plan, satellite basemap, or the 3D model. */
type ViewMode = "plan" | "satellite" | "3d";

/** Right toolbar group — view modes, each shown as a thumbnail button (Layers-button visual). The thumbnails
 *  are bundled into the design system (inline data-URIs in `./view-mode-thumbs`), so they're a constant of
 *  the template and need no host-served public files. */
const MODE_TABS: {id: ViewMode; label: string; icon: typeof Home; thumb: string}[] = [
	{id: "3d", label: "Reality", icon: Box, thumb: DRONE_THUMB},
	{id: "plan", label: "Plan", icon: MapIcon, thumb: PLAN_THUMB},
];

type LevelId = "block" | "batch" | "zone" | "phase";

/** Grouping levels for the "Batch" slot — a hover dropdown swaps the slot's label + icon. Ordered finest →
 *  coarsest: Block → Batch → Zone → Phase. */
const LEVELS: {id: LevelId; label: string; noun: string; icon: typeof Home}[] = [
	{id: "block", label: "Block", noun: "blocks", icon: Boxes},
	{id: "batch", label: "Batch", noun: "batches", icon: LayoutGrid},
	{id: "zone", label: "Zone", noun: "zones", icon: MapIcon},
	{id: "phase", label: "Phase", noun: "phases", icon: Layers},
];

/** Prefix shown on each filter chip so the value reads in context (e.g. "Block: Block-02", "Milestone: M50"). */
const FILTER_KIND_LABEL: Record<CaptureFilter["kind"], string> = {
	batch: "Batch",
	block: "Block",
	milestone: "Milestone",
	variance: "Variance",
};

/* ------------------------------------------------------------------ *
 * Preview
 * ------------------------------------------------------------------ */

/**
 * Optional data seam. Every field defaults to the bundled ALMANAR fixtures, so `<CaptureUiEnhanced />`
 * renders unchanged (Storybook). A host (e.g. Capture) passes real data through these props:
 * - `zoneViews`: per-location villa overlays (polygons + list rows + blueprint image) for the site map,
 *   villa list, zone summary and distribution.
 * - `allVillas`: the full villa set the Milestone Progression grid colours one block per villa.
 */
/**
 * Payload passed to the detail-rail callback seams (`onOpenBlueprints`, `onOpenWalkthrough`,
 * `onOpenProgressDetails`). A host maps the selected villa's linked LBS item + plot back to its own routing.
 */
export type CaptureDetailVilla = {
	id: number | string;
	lbsItemId: number | null;
	name: string;
	plotNumber: string;
};

export type CaptureUiEnhancedProps = {
	zoneViews?: Record<string, ZoneVillaView>;
	allVillas?: SiteVilla[];
	/** Batch / Zone / Phase overlays (the "Batch" level toggle) — each its own polygons + blueprint image. */
	levelViews?: Partial<Record<LevelId, ZoneVillaView>>;
	/** Block-level overlays, keyed by location (zone) — the Block level is per-zone (each zone's own blueprint). */
	blockViews?: Record<string, ZoneVillaView>;
	/** Satellite basemaps swapped in by the Satellite toggle (villa = whole-area, zone = zone satellite). */
	satelliteViews?: {villa?: SatelliteBasemap; zone?: SatelliteBasemap};
	/** Drill-down navigator tree (Zone → Batch → Villa). Leaf ids must match the `zoneViews` villa ids. */
	navNodes?: CanvasNavigatorNode[];
	/** Navigator leaf villa id → its zone id, so selecting a villa switches to the right zone first. */
	villaZoneById?: Map<string, string>;
	/** Timeline scrubber weeks (real reporting periods) — defaults to the synthetic fixture axis. */
	timeline?: TimelineWeek[];
	/** Initially-selected week `value` (must exist in `timeline`); defaults to the fixture's week 122. */
	initialWeek?: string;
	/**
	 * Real milestone-progression grid values — one entry per month (aligned to the 6 offsets -3..+2), each
	 * carrying per-villa `actualPercent`/`plannedPercent` in `allVillas` order (`null` = no data → muted).
	 * When present, replaces the synthetic `approvedProgressPercent + offset*MONTH_STEP` colouring.
	 */
	progressionData?: {
		actualPercent: (number | null)[];
		plannedPercent: (number | null)[];
	}[];
	/** Force the artificial map loading effect (zoom-out + blur + spinner) ON — e.g. tied to a host's real async load. */
	mapLoading?: boolean;
	/** Detail-rail "Blueprints" action — when set, opens the host viewer instead of the internal fixture dialog. */
	onOpenBlueprints?: (villa: CaptureDetailVilla) => void;
	/** Detail-rail "360 Walkthrough" action — when set, the button invokes this. */
	onOpenWalkthrough?: (villa: CaptureDetailVilla) => void;
	/** Detail-rail "Progress Details" action — when set, the button invokes this. */
	onOpenProgressDetails?: (villa: CaptureDetailVilla) => void;
	/** Hide the "Floors" detail tab (trigger + body). Defaults to shown. */
	hideFloors?: boolean;
	/** Hide the "Evidence" detail tab (trigger + body). Defaults to shown. */
	hideEvidence?: boolean;
	/** Hide the "Activities" detail tab (trigger + body). Defaults to shown. */
	hideActivities?: boolean;
	/** Hide the 3D map-mode toggle so the user can't switch to 3D. Defaults to shown. */
	hide3d?: boolean;
	/** In the Reports sheet, render only the milestone-progression hero and hide all other report sections. */
	showOnlyProgressionReport?: boolean;
	/** Hide the villa detail "Milestones" header + grid (fixture-backed). Defaults to shown. */
	hideMilestones?: boolean;
	/** Hide the global rail search input + its (fixture-backed) full-height results panel. Defaults to shown. */
	hideSearch?: boolean;
};

export function CaptureUiEnhanced(props: CaptureUiEnhancedProps = {}) {
	// Resolve each data source from props. Anti-fixture-leak: when a host supplies a data prop it is used
	// VERBATIM and NEVER merged with the bundled fixtures — a missing key/entry renders EMPTY, never fixture
	// content. The fixture defaults apply only when the host omits the whole prop (`undefined`).
	const ZONE_VILLA_VIEWS = props.zoneViews ?? ZONE_VILLA_VIEWS_DEFAULT;
	const ALL_VILLAS = props.allVillas ?? ALL_VILLAS_DEFAULT;
	// Site-wide plot → { location (zone key), id } lookup. The 3D scene shows EVERY villa across both zones,
	// but the rail/detail is scoped to the current zone — so a 3D click must resolve the plot across ALL zones
	// (not just the active one) and switch zones when the villa lives in the other one. Without this, clicking
	// a villa outside the current zone selects it in 3D (graying the rest) but never opens details, leaving it
	// stuck-selected — which also makes the SPA/Progress recolour look dead (everything stays gray).
	const villaByPlot = useMemo(() => {
		const m = new Map<string, {location: string; id: string}>();
		for (const [location, view] of Object.entries(ZONE_VILLA_VIEWS)) {
			for (const r of view.rows) {
				const plot = r.name.match(/^\d+/)?.[0];
				if (plot && !m.has(plot)) m.set(plot, {location, id: r.id});
			}
		}
		return m;
	}, [ZONE_VILLA_VIEWS]);
	// Host-provided levelViews are used as-is (a missing level resolves to EMPTY_VIEW at the lookup below);
	// fixture level entries are NOT merged in.
	const LEVEL_VIEW: Partial<Record<LevelId, ZoneVillaView>> = props.levelViews ?? LEVEL_VIEW_DEFAULT;
	// Block level is per-zone (each zone's blocks live in that zone's own blueprint pixel space).
	const BLOCK_VIEWS = props.blockViews ?? BLOCK_VIEWS_DEFAULT;
	// When the host supplies satelliteViews, a missing basemap stays absent (null) — never the fixture.
	const VILLA_SATELLITE: SatelliteBasemap | null = props.satelliteViews
		? (props.satelliteViews.villa ?? null)
		: VILLA_SATELLITE_DEFAULT;
	const ZONE_SATELLITE: SatelliteBasemap | null = props.satelliteViews
		? (props.satelliteViews.zone ?? null)
		: ZONE_SATELLITE_DEFAULT;
	// `??` falls back only when navNodes is `undefined`; a host-provided array (even empty) is used verbatim.
	const NAV_NODES = props.navNodes ?? NAV_NODES_DEFAULT;
	const NAV_VILLA_ZONE = props.villaZoneById ?? NAV_VILLA_ZONE_DEFAULT;
	const TIMELINE_WEEKS = props.timeline && props.timeline.length > 0 ? props.timeline : TIMELINE_WEEKS_DEFAULT;

	const [screen] = useState<string>("screen-1");

	// Search text (lifted from SitePanel so it can filter the MAP + 3D, not just the rail list). The single
	// `visible*` derivation below turns this — and the filter chips — into one subset fed to every surface.
	const [query, setQuery] = useState("");
	// Structured search filters (batch / block / milestone / variance) — chips render under the toolbar; they
	// narrow the same `visible*` villa set as the query. Batch/block options are scoped to the current zone.
	const [filters, setFilters] = useState<CaptureFilter[]>([]);
	// The full-height results panel: `searchOpen` toggles it; `searchLevels` is the active level filter
	// (empty = all levels). Typing (with a non-empty query, panel closed) collapses the rail to the search
	// box + two scope options, which open the panel filtered to the current level or to all.
	const [searchOpen, setSearchOpen] = useState(false);
	const [selectedId, setSelectedId] = useState("");
	// Shared SPA (progress) / Construction (variance) colour mode — drives the map AND the distribution card.
	const [mapMode, setMapMode] = useState<MapMode>("progress");
	// Two independent axes drive the canvas: `view` is the LBS level (Villa / Batch, left toolbar group), and
	// `mode` is how it's rendered (Plan / Satellite / 3D, right toolbar group). Opens in Reality (3D), which
	// always sits at villa level (view "villa" / level "batch") — switching to Plan drops to the phase level.
	const [view, setView] = useState<ViewId>("villa");
	const [mode, setMode] = useState<ViewMode>("3d");
	// The grouping level for the "Batch" slot (Batch / Zone / Phase) — a hover dropdown swaps its label + icon.
	const [level, setLevel] = useState<LevelId>("batch");
	const activeLevel = LEVELS.find((l) => l.id === level) ?? LEVELS[0];
	const [currentLocation, setCurrentLocation] = useState("zone-1-a");
	const locationIndex = Math.max(
		0,
		LOCATIONS.findIndex((l) => l.id === currentLocation),
	);
	const currentLoc = LOCATIONS[locationIndex] ?? LOCATIONS[0];
	// Live handle to the 3D viewer so mode switches can read its zoom + selection to pick the matching LBS level.
	const realityViewerRef = useRef<FootprintViewer | null>(null);
	// 3D-view layer controls (driven from the Layers overlay): the reality mesh and the progress model each
	// toggle + fade independently, and the progress colouring toggles on/off.
	const [mesh3dOn, setMesh3dOn] = useState(true);
	const mesh3dOpacity = 1; // reality mesh fully opaque; no opacity slider (toggle only)
	const [model3dOn, setModel3dOn] = useState(true);
	const [model3dOpacity, setModel3dOpacity] = useState(0.85);
	const [progressColours, setProgressColours] = useState(true);
	// The 3D reality model is expensive to load, so once it's up we keep it mounted while the user stays at the
	// villa level (toggling between the 3D and 2D plan views just hides/shows it). It only unloads when the user
	// jumps up to a parent grouping (zone/phase) — see the effect below that resets this when `level` leaves batch.
	const [threeDLoaded, setThreeDLoaded] = useState(true); // opens in Reality, so the 3D pane starts mounted
	// A one-line toast under the toolbar, shown when the top-bar jumps down to the villa level. `jumpToast`
	// holds the destination label (e.g. "Zone 1 – A"); `jumpToastLeaving` plays the exit before it unmounts.
	const [jumpToast, setJumpToast] = useState<string | null>(null);
	const [jumpToastLeaving, setJumpToastLeaving] = useState(false);
	const jumpToastTimers = useRef<number[]>([]);
	const showJumpToast = (label: string) => {
		jumpToastTimers.current.forEach((t) => window.clearTimeout(t));
		setJumpToast(label);
		setJumpToastLeaving(false);
		jumpToastTimers.current = [
			window.setTimeout(() => setJumpToastLeaving(true), 2200), // start the exit
			window.setTimeout(() => {
				setJumpToast(null);
				setJumpToastLeaving(false);
			}, 2500), // unmount after it finishes
		];
	};

	// Every map-content change (view mode, grouping level, or location) runs the SAME orchestrated
	// transition: zoom the current map out to the grey frame + show a spinner (~500ms load), then apply the
	// change so the new content mounts at that zoomed-out + blurred start, and finally zoom-to-fit while the
	// blur fades. `mapPhase`: idle → out → in. `mapEntering` holds the incoming map at the start for a frame
	// so the CSS transition to fit/unblur actually runs.
	// The map/canvas "reload" transition (zoom-out → blur → spinner → zoom-back-in), now the shared
	// useMapTransition() primitive (@corensystem/core-ui/map-transition). `mapTx.run(apply)` swaps content at
	// the zoomed-out midpoint; BuildingViewer renders the visual from the derived flags below.
	const mapTx = useMapTransition();
	// Left group — pick the LBS level. Choosing a level implies a 2D view, so leave the 3D model for the plan.
	const selectView = (id: ViewId) => {
		if (id === view && mode !== "3d") return;
		// Toast only when dropping from a COARSE level (Zone/Phase) down to the villas. Batch and Block are fine
		// levels that toggle freely with Villa, so those get no "jumped to Zone A" toast.
		if (id === "villa" && view === "batch" && level !== "batch" && level !== "block") showJumpToast(currentLoc.label);
		const apply = () => {
			setView(id);
			// Villa pairs with the last-chosen fine level: Batch by default, or Block if the user picked it. Only the
			// coarse levels (Zone/Phase) fall back to Batch so the Villa/parent toggle has a fine level to bounce to.
			if (id === "villa" && level !== "batch" && level !== "block") setLevel("batch");
			// Selection is per-level (villa ids ≠ batch ids), so clear it and close the detail panel on switch.
			setSelectedId("");
			setDetailOpen(false);
			if (mode === "3d") setMode("plan");
		};
		// Villa ↔ Batch are quick 2D aerial swaps — switch instantly. Leaving the 3D model runs the load transition.
		if (mode === "3d") mapTx.run(apply);
		else apply();
	};
	// Right group — pick the render mode. Plan ↔ Satellite is an instant basemap swap; to/from 3D runs the load
	// transition. Reality ALWAYS sits at villa level (the sidebar keeps the villa list, even at the default
	// zoomed-out view). Switching Reality → Plan syncs the level to the 3D camera:
	//   • a villa is selected, or the camera is zoomed past the default → Villa level
	//   • at the default (zoomed-out) view                              → Site/phase level (Almanar)
	const toVillaLevel = () => {
		setView("villa");
		// Preserve the fine level (Batch/Block); only coarse levels (Zone/Phase) fall back to Batch.
		if (level !== "batch" && level !== "block") setLevel("batch");
	};
	const toSiteLevel = () => {
		setView("batch");
		setLevel("phase");
		setSelectedId("");
		setDetailOpen(false);
	};
	const selectMode = (m: ViewMode) => {
		if (m === mode) return;
		if (m === "satellite" && !satelliteBasemap) return;
		const leaving3d = mode === "3d";
		const entering3d = m === "3d";
		const villaSelected = !!(selectedId && detailOpen);
		const apply = () => {
			setMode(m);
			if (entering3d) {
				// The 3D model is always progress-coloured — keep the list + distribution in step.
				setMapMode("progress");
				setThreeDLoaded(true);
				// Reality always sits at villa level so the villa list is always available (a selected villa is kept).
				toVillaLevel();
			} else if (leaving3d) {
				// Reality → Plan: the default (zoomed-out) view drops to the phase/site level; any zoom-in (or a
				// selected villa) stays at villa level.
				const zoomedIn = realityViewerRef.current?.isZoomedIn() ?? false;
				if (villaSelected || zoomedIn) {
					toVillaLevel(); // keep any selection so its details show in 2D
				} else {
					toSiteLevel();
				}
			}
		};
		if (entering3d || leaving3d) mapTx.run(apply);
		else apply();
	};
	const selectLevel = (id: LevelId) => {
		if (id === level && view === "batch" && mode !== "3d") return;
		const apply = () => {
			setLevel(id);
			setView("batch");
			setSelectedId("");
			setDetailOpen(false);
			if (mode === "3d") setMode("plan");
		};
		// Block / Batch / Villa are the fine adjacent levels — swap between them INSTANTLY (no zoom/blur). Zone and
		// Phase are the big context jumps (and leaving 3D), so those still run the load transition.
		if ((id === "batch" || id === "block") && mode !== "3d") apply();
		else mapTx.run(apply);
	};
	const stepLocation = (delta: number) => {
		const next = LOCATIONS[(locationIndex + delta + LOCATIONS.length) % LOCATIONS.length].id;
		if (next === currentLocation) return;
		mapTx.run(() => setCurrentLocation(next));
	};
	// The map wrapper is CSS-scaled + blurred (a `filter: blur` on the map only — not a backdrop overlay, so
	// the surrounding UI stays crisp). Both are active across the whole transition: `transition-all` fades
	// the blur IN as the current map zooms out, holds it through the load, then fades it OUT as the new zone
	// zooms to fit. `mapEntering` keeps the incoming map at the blurred+zoomed-out start for one frame.
	const mapScaledOut = mapTx.scaledOut || !!props.mapLoading;
	const mapBlurred = mapTx.blurred || !!props.mapLoading;
	// Keep the 3D model mounted whenever it's in view OR loaded and still at the villa/batch level, so the
	// 3D ↔ 2D-plan toggle only shows/hides it (never re-fetches the mesh).
	// Keep the 3D viewer mounted (hidden) once it's loaded so toggling Plan/Reality never re-streams the mesh,
	// and the page can still read its zoom/selection at any level when switching modes.
	const keep3dMounted = mode === "3d" || threeDLoaded;
	const [detailOpen, setDetailOpen] = useState(false);
	const closeDetail = () => {
		setDetailOpen(false);
	};
	const [capture, setCapture] = useState(
		props.initialWeek ?? TIMELINE_WEEKS[TIMELINE_WEEKS.length - 1]?.value ?? "122",
	);
	// `initialWeek` arrives after the real periods load (async); sync the selected week to it once so the
	// timeline + progression grid anchor on the real current period instead of the first fixture week.
	useEffect(() => {
		if (props.initialWeek) setCapture(props.initialWeek);
	}, [props.initialWeek]);
	// Villa detail rail — active tab (Overview / Floors / Evidence / Activities).
	const [detailTab, setDetailTab] = useState("overview");
	// Timeline (bottom-centre): the selected week drives the date-range label. The draggable WeekTimeline
	// component owns the scrub/flow/snap interaction and reports the selected week back via setCapture.
	const captureIndex = Math.max(
		0,
		TIMELINE_WEEKS.findIndex((w) => w.value === capture),
	);
	const selectedWeek = TIMELINE_WEEKS[captureIndex] ?? TIMELINE_WEEKS[TIMELINE_WEEKS.length - 1];
	const rangeLabel = `${fmtDate(selectedWeek.start)} – ${fmtDate(selectedWeek.end)}`;
	// "Reports" opens a report sheet that animates up over the map; as it slides up the map darkens + blurs.
	// Content is placeholder (to be replaced). The sheet's own body scrolls once it's up.
	const [reportsOpen, setReportsOpen] = useState(false);
	// All the map chrome (rail, view switcher, layers, toolbar, detail rail, viewer controls) fades out while
	// the reports sheet is up, so only the (blurred) map shows behind it.
	const chromeFade = cn(
		"wwc:transition-opacity wwc:duration-500",
		reportsOpen && "wwc:pointer-events-none wwc:opacity-0",
	);
	// Reports layout (at rest = scroll 0): grid hero 80% · 5% gap · report peek 15%. Scrolling moves the whole
	// page together — the map translates up 1:1 (see below) so it scrolls away rather than the sheet overlaying.
	const [reportScrollY, setReportScrollY] = useState(0);
	// Unload the 3D model when the user leaves the fine levels (Villa/Batch/Block) for a coarse grouping
	// (Zone/Phase). Staying on a fine level keeps it mounted so the 3D ↔ 2D-plan toggle never re-fetches the mesh.
	useEffect(() => {
		if (level !== "batch" && level !== "block") setThreeDLoaded(false);
	}, [level]);
	const firstWeek = TIMELINE_WEEKS[0];
	const lastWeek = TIMELINE_WEEKS[TIMELINE_WEEKS.length - 1];
	// Map layers now live in an overlay ON the canvas, toggled by the Layers button — closed to start.
	const [blueprintsOpen, setBlueprintsOpen] = useState(false);

	// The floating left panel overlays the map. When its content fills the full canvas height the
	// Layers control can't sit under it, so it shifts to sit BESIDE the sidebar; otherwise it rests
	// in the bottom-left corner under the sidebar. We measure the rendered panel vs. the canvas.
	const bodyRef = useRef<HTMLDivElement>(null);
	// Mutable so SitePanel's onPanelResize callback-ref can write it (the rail element lives inside the widget now).
	const panelRef = useRef<HTMLDivElement | null>(null);
	const [sidebarFull, setSidebarFull] = useState(false);
	// Cap the floating panel to the canvas height (measured, not a % — an absolutely-positioned
	// element resolves % heights against the viewport here, not the body). It's "full" when its
	// natural content would overflow that cap.
	const [maxPanelH, setMaxPanelH] = useState<number | undefined>(undefined);
	useLayoutEffect(() => {
		const measure = () => {
			const body = bodyRef.current;
			const panel = panelRef.current;
			if (!body || !panel) return;
			const avail = body.clientHeight - 24; // 12px top + 12px bottom insets
			setMaxPanelH(avail);
			setSidebarFull(panel.scrollHeight > avail + 2);
		};
		measure();
		const ro = new ResizeObserver(measure);
		if (bodyRef.current) ro.observe(bodyRef.current);
		if (panelRef.current) ro.observe(panelRef.current);
		window.addEventListener("resize", measure);
		return () => {
			ro.disconnect();
			window.removeEventListener("resize", measure);
		};
	}, [currentLocation, detailOpen, query]);
	// Map-overlay toggles for the 2D viewer — the map-layers control exposes whichever apply to what's drawn.
	const [showPolygons, setShowPolygons] = useState(true);
	const [showLabels, setShowLabels] = useState(true);

	// The "Batch" slot draws grouping polygons (Batch/Zone/Phase); Villa overlays the 301 footprints. This
	// drives the left rail (list, count, distribution, zone). The Satellite toggle only swaps the canvas
	// basemap for the selected context — it doesn't change the rail.
	const isParent = view === "batch";
	// The current-location card reflects where you actually are — the parent context of what the map shows:
	//  • batch level (villas / batches of a zone) → the zone itself (e.g. "Zone 1 – A")
	//  • zone level  (the zones of the phase)      → "Phase 1"
	//  • phase level (the phases of the site)      → "Almanar" (the site / project root)
	// Block + Batch both sit within the current zone, so their location card reads that zone; Zone → Phase 1; Phase → Almanar.
	const locationLabel =
		level === "batch" || level === "block" ? currentLoc.label : level === "zone" ? "Phase 1" : "Almanar";
	// Block is location-aware (per zone); the other parent levels are single site-wide views. A missing view
	// (host levelViews/blockViews without this key) renders an empty view — never the fixture.
	const levelView =
		level === "block"
			? (BLOCK_VIEWS[currentLocation] ?? BLOCK_VIEWS["zone-1-a"] ?? Object.values(BLOCK_VIEWS)[0] ?? EMPTY_VIEW)
			: (LEVEL_VIEW[level] ?? EMPTY_VIEW);
	// The villa view draws the current zone's overlay (the location stepper picks Zone 1-A vs 1-B). Guard at
	// the source so the villa view NEVER throws even when no zone view matches the current location.
	const zoneVilla: ZoneVillaView =
		ZONE_VILLA_VIEWS[currentLocation] ??
		ZONE_VILLA_VIEWS["zone-1-a"] ??
		Object.values(ZONE_VILLA_VIEWS)[0] ??
		EMPTY_VIEW;
	// The full set drawn at this view/level (villa footprints, or the grouping polygons). Selection/detail always
	// resolve against this full set so a search that hides the open villa never drops or reassigns it.
	const activeRowsFull = isParent ? levelView.rows : zoneVilla.rows;
	const drawnVillas = isParent ? levelView.villas : zoneVilla.villas;
	// ── The one filter seam ──────────────────────────────────────────────────────────────────────────────
	// A row is "visible" when it satisfies the active search text AND every active filter chip.
	// `visibleRows` drives the rail list + count + distribution; `visibleVillas` drives the 2D polygons;
	// `visiblePlots` drives the 3D footprints — so search + filters narrow EVERYTHING on screen, not just the list.
	const q = query.trim().toLowerCase();
	// Group active filters by kind: within a kind ANY value matches (OR — e.g. Block-01 OR Block-02), across
	// kinds ALL must match (AND — e.g. Batch-01 AND behind). Milestone/variance read the row's own progress so
	// they apply at any level; batch/block resolve via the villa's plot, so on parent rows (no plot) they no-op.
	const filtersByKind = useMemo(() => {
		const m: Record<CaptureFilter["kind"], string[]> = {batch: [], block: [], milestone: [], variance: []};
		for (const f of filters) m[f.kind].push(f.value);
		return m;
	}, [filters]);
	const rowMatchesFilters = (r: Villa): boolean => {
		const plot = r.name.match(/^\d+/)?.[0];
		if (filtersByKind.milestone.length && !filtersByKind.milestone.includes(approvedProgressToBucket(r.approved)))
			return false;
		if (filtersByKind.variance.length && !filtersByKind.variance.includes(classifyVariance(r.approved, r.planned)))
			return false;
		if (plot && filtersByKind.batch.length && !filtersByKind.batch.includes(ALMANAR_VILLA_BATCH[plot])) return false;
		if (plot && filtersByKind.block.length && !filtersByKind.block.includes(ALMANAR_VILLA_BLOCK_NAME[plot]))
			return false;
		return true;
	};
	const rowVisible = (r: Villa) =>
		(!q || r.name.toLowerCase().includes(q) || r.meta.toLowerCase().includes(q)) && rowMatchesFilters(r);
	const filterActive = q.length > 0 || filters.length > 0;
	const visibleRows = filterActive ? activeRowsFull.filter(rowVisible) : activeRowsFull;
	// Match a drawn footprint back to its row id the same way the rows were derived (parent = linked LBS item).
	const villaRowId = (v: SiteVilla) => (isParent ? String(v.linkedLbsItemId ?? v.id) : String(v.id));
	const visibleRowIds = useMemo(() => new Set(visibleRows.map((r) => r.id)), [visibleRows]);
	const visibleVillas = filterActive ? drawnVillas.filter((v) => visibleRowIds.has(villaRowId(v))) : drawnVillas;
	// 3D whitelist: the visible villas' plot numbers (leading digits of the name — the key the viewer indexes by,
	// matching `selectedNumber`/`selectedPlot`). `null` = no filter (show every footprint).
	const visiblePlots: string[] | null = filterActive
		? visibleVillas.map((v) => v.name.match(/^\d+/)?.[0] ?? v.plotNumber).filter((p): p is string => Boolean(p))
		: null;
	const unitNoun = isParent ? activeLevel.noun : "villas";
	const unitNounSingular = isParent ? activeLevel.label.toLowerCase() : "villa";
	const countNoun = visibleRows.length === 1 ? unitNounSingular : unitNoun;

	// Filter menu options: batch + block scoped to the current zone; milestone (SPA ramp) + variance from the
	// shared legends (same ids the map colours use, so a filter lines up 1:1 with a legend bucket).
	const filterOptions: CaptureFilterOptions = useMemo(
		() => ({
			batches: (ALMANAR_BATCHES_BY_ZONE[currentLocation] ?? []).map((name) => ({value: name, label: name})),
			blocks: (ALMANAR_BLOCKS_BY_ZONE[currentLocation] ?? []).map((name) => ({value: name, label: name})),
			milestones: PROGRESS_LEGEND_ITEMS.filter((i) => i.id.startsWith("ms")).map((i) => ({
				value: i.id,
				label: i.label,
			})),
			variances: VARIANCE_LEGEND_ITEMS.filter((i) => ["behind", "onTrack", "ahead"].includes(i.id)).map((i) => ({
				value: i.id,
				label: i.label,
			})),
		}),
		[currentLocation],
	);

	// The satellite basemap for the current context, if any: Villa (Zone 1-A only — 1-B has no satellite
	// blueprint) → clean whole-area satellite; Zone → the zone satellite blueprint. Batch/Phase and Drone
	// have none, so the toggle is disabled there.
	const satelliteBasemap: SatelliteBasemap | null =
		view === "villa" && currentLocation === "zone-1-a"
			? VILLA_SATELLITE
			: view === "batch" && level === "zone"
				? ZONE_SATELLITE
				: null;
	const hasSatellite = satelliteBasemap !== null;

	// Map-layers control — the toggles reflect what's actually drawn on the current view. For a 2D polygon
	// view (Villa / Batch / Zone / Phase) you can turn the plot polygons and their labels off; the Satellite
	// basemap and the Drone model have no polygon overlay, so those show read-only rows instead.
	const polyNoun = view === "villa" ? "Villa" : activeLevel.label;

	const selected = activeRowsFull.find((v) => v.id === selectedId) ?? activeRowsFull[0];
	// Villa number only (e.g. "2027" from "2027 DP1-L") + its full hierarchy path (file-path style).
	const selectedNumber = selected.name.match(/^\d+/)?.[0] ?? selected.name;
	const selectedBatch = (ALMANAR_HIERARCHY[currentLocation] ?? []).find((b) => b.villaNumbers.includes(selectedNumber));
	// Block sits between batch and villa (Zone → Batch → Block → Villa); omit the segment when no block was captured.
	const selectedBlock = ALMANAR_VILLA_BLOCK[selectedNumber];
	const selectedPath = [
		"Phase 1",
		currentLoc.label,
		selectedBatch?.name,
		selectedBlock ? `Block ${selectedBlock}` : undefined,
		selected.name,
	]
		.filter(Boolean)
		.join(" / ");
	const distribution = useMemo(() => distributionFor(visibleRows, mapMode), [visibleRows, mapMode]);
	// Map the selected list row back to its footprint (SiteVilla) so the detail-rail callbacks can hand the host
	// the linked LBS item + plot number. Batch-level rows have no footprint match → lbsItemId null, plot "".
	const selectedSiteVilla = zoneVilla?.villas.find((v) => String(v.id) === selected.id);
	const detailVilla: CaptureDetailVilla = {
		id: selected.id,
		lbsItemId: selectedSiteVilla?.linkedLbsItemId ?? null,
		name: selected.name,
		plotNumber: selectedSiteVilla?.plotNumber ?? "",
	};

	// If a hidden detail tab is the active one, fall back to Overview (Overview is never hideable).
	useEffect(() => {
		if (
			(props.hideFloors && detailTab === "floors") ||
			(props.hideEvidence && detailTab === "evidence") ||
			(props.hideActivities && detailTab === "activities")
		) {
			setDetailTab("overview");
		}
	}, [props.hideFloors, props.hideEvidence, props.hideActivities, detailTab]);

	// When 3D is hidden, never leave the map stuck in 3D — fall back to the plan view.
	useEffect(() => {
		if (props.hide3d && mode === "3d") setMode("plan");
	}, [props.hide3d, mode]);

	const openVilla = (id: string) => {
		setSelectedId(id);
		setDetailOpen(true);
	};

	// BuildingViewer funnels both the 3D footprint click (a plot number) and the 2D leaf-polygon click (a row
	// id) through one onSelectVilla. Resolve the plot across all zones first (hopping to the villa's zone if it
	// isn't the active one); a 2D row id isn't a plot key, so it falls through to a plain openVilla.
	const handleSelectVilla = (idOrPlot: string) => {
		const hit = villaByPlot.get(idOrPlot);
		if (hit) {
			if (hit.location !== currentLocation) setCurrentLocation(hit.location);
			openVilla(hit.id);
			return;
		}
		openVilla(idOrPlot);
	};
	// The widget lazily creates the footprint viewer and surfaces it here so selectMode's leaving-3D branch can
	// read its zoom (isZoomedIn) to pick the matching LBS level.
	const handleViewerReady = (api: FootprintViewer) => {
		realityViewerRef.current = api;
	};

	// Canvas-navigator select as a node handler (SitePanel resolves the id → node and forwards it). Same
	// zone / batch / villa-leaf routing the inline navigator used; the widget owns navigatorOpen now, so
	// this no longer toggles it closed.
	const handleNavigate = (node: CanvasNavigatorNode) => {
		const id = node.id;
		if (LOCATIONS.some((l) => l.id === id)) {
			if (id !== currentLocation || view !== "villa") {
				mapTx.run(() => {
					setCurrentLocation(id);
					setView("villa");
					setLevel("batch");
				});
			}
			return;
		}
		// Batch and Block are both grouping branches (id `batch::<zone>::…` / `block::<zone>::…::<block>`): selecting
		// either drills into that zone's villa view (the block is a nesting level, not its own map level).
		if (id.startsWith("batch::") || id.startsWith("block::")) {
			const zoneOfGroup = id.split("::")[1];
			mapTx.run(() => {
				setCurrentLocation(zoneOfGroup);
				setView("villa");
				setLevel("batch");
			});
			return;
		}
		const zoneOfVilla = NAV_VILLA_ZONE.get(id);
		if (zoneOfVilla) {
			mapTx.run(() => {
				setCurrentLocation(zoneOfVilla);
				setView("villa");
				setLevel("batch");
				setSelectedId(id);
				setDetailOpen(true);
			});
		}
	};

	// Drill down one level on a parent-polygon click: phase → zone → villa. (Batch and villa are the same
	// level in different views, so zone/batch both drop straight to the villa view.) Clicking a specific zone
	// carries its location into the villa view (and remembers it), so it lands on that zone — not always A.
	const drillDownLevel = (id: string) => {
		// Block → villa is an INSTANT swap (no zoom-out/blur transition) that also applies the clicked block as a
		// filter, so the villa view lands pre-narrowed to that block (chip appears; clicking more blocks accumulates).
		if (level === "block") {
			const name = levelView.rows.find((r) => r.id === id)?.name;
			// Stay on the Block fine level (don't reset to Batch) so the Villa/Block toggle bounces straight back.
			setView("villa");
			if (name) {
				setFilters((prev) =>
					prev.some((f) => f.kind === "block" && f.value === name)
						? prev
						: [...prev, {kind: "block", value: name, label: name}],
				);
			}
			return;
		}
		if (level === "phase") {
			mapTx.run(() => setLevel("zone"));
			return;
		}
		const loc = ZONE_LOCATION_BY_ID[id];
		mapTx.run(() => {
			if (loc) setCurrentLocation(loc);
			setView("villa");
			// Villa and Batch are the same level, so the parent toggle should read "Batch" (not the "Zone" we
			// drilled through) once we land on the villa view.
			setLevel("batch");
		});
	};

	return (
		<div className="wwc:flex wwc:h-full wwc:w-full wwc:flex-col wwc:overflow-hidden wwc:bg-background wwc:text-foreground">
			{/* ---------------- Body: map canvas · floating panels · detail rail ----------------
          `relative` is the positioning context for the floating left panel + layers overlay, and
          `bodyRef` measures the available canvas height for the sidebar-fills-the-page logic. */}
			<div ref={bodyRef} className="wwc:relative wwc:flex wwc:min-h-0 wwc:flex-1 wwc:flex-row wwc:overflow-hidden">
				{screen === "screen-1" && (
					<>
						<SitePanel
							view={view}
							mode={mode}
							level={level}
							activeLevel={activeLevel}
							currentLocation={currentLocation}
							locationLabel={locationLabel}
							locationIndex={locationIndex}
							isParent={isParent}
							activeRows={visibleRows}
							unitNoun={unitNoun}
							unitNounSingular={unitNounSingular}
							countNoun={countNoun}
							selectedId={selectedId}
							detailOpen={detailOpen}
							detailVilla={detailVilla}
							selected={selected}
							selectedNumber={selectedNumber}
							selectedPath={selectedPath}
							mapMode={mapMode}
							distribution={distribution}
							navNodes={NAV_NODES}
							chromeFade={chromeFade}
							maxPanelH={maxPanelH}
							hideFloors={props.hideFloors}
							hideEvidence={props.hideEvidence}
							hideActivities={props.hideActivities}
							hideMilestones={props.hideMilestones}
							hideSearch={props.hideSearch}
							searchOpen={searchOpen}
							query={query}
							onQueryChange={setQuery}
							filters={filters}
							onFiltersChange={setFilters}
							filterOptions={filterOptions}
							captureId={capture}
							rangeLabel={rangeLabel}
							onSelectVilla={openVilla}
							onCloseDetail={closeDetail}
							onStepLocation={stepLocation}
							onNavigate={handleNavigate}
							onDrillDown={drillDownLevel}
							onMapModeChange={setMapMode}
							onSearchOpenChange={setSearchOpen}
							onPanelResize={(el) => {
								panelRef.current = el as HTMLDivElement | null;
							}}
							onOpenBlueprints={props.onOpenBlueprints}
							onOpenWalkthrough={props.onOpenWalkthrough}
							onOpenProgressDetails={props.onOpenProgressDetails}
						/>

						{/* Map canvas (base layer) — the real Site Image Viewer widget: the ROSHN Almanar aerial
                ("Zone 1 - A") with the real villa footprint polygons coloured by construction progress.
                The widget owns its own hover progress card + SPA/Construction legend. The floating left
                panel above and the map-layers overlay below sit ON TOP of it. Background image is served
                by the app (apps/storybook/public/site-background.webp). */}
						<BuildingViewer
							mode={mode}
							view={view}
							level={level}
							currentLocation={currentLocation}
							isParent={isParent}
							map={{
								villas: visibleVillas,
								// This zone's block hulls (same pixel space as the villas). BuildingViewer only feeds these to
								// the villa (leaf) view, where the plan shows block-name labels while zoomed out and swaps to
								// villa chips once zoomed in past 10% — matching the 3D reality view's LOD hand-off.
								blocks: BLOCK_VIEWS[currentLocation]?.villas,
								backgroundUrl: isParent ? levelView.backgroundUrl : zoneVilla.backgroundUrl,
								imageWidth: isParent ? levelView.imageWidth : zoneVilla.imageWidth,
								imageHeight: isParent ? levelView.imageHeight : zoneVilla.imageHeight,
								// Block shares the villa view's key (same image + coordinate space per zone) so villa ↔ block
								// only swaps polygons — no SiteImageViewer remount, no image reload.
								contentKey: isParent && level !== "block" ? level : `villa-${currentLocation}`,
							}}
							satelliteBasemap={satelliteBasemap}
							selectedVillaId={detailOpen && !isParent ? selectedId : undefined}
							selectedPlot={detailOpen && selectedId ? selectedNumber : undefined}
							visiblePlots={visiblePlots}
							mapMode={mapMode}
							mesh3dOn={mesh3dOn}
							mesh3dOpacity={mesh3dOpacity}
							model3dOn={model3dOn}
							model3dOpacity={model3dOpacity}
							progressColours={progressColours}
							showLabels={showLabels}
							showPolygons={showPolygons}
							keep3dMounted={keep3dMounted}
							mapScaledOut={mapScaledOut}
							mapBlurred={mapBlurred}
							showSpinner={mapTx.showSpinner || !!props.mapLoading}
							chromeHidden={reportsOpen}
							chromeFade={chromeFade}
							reportScrollY={reportScrollY}
							jumpToast={jumpToast}
							jumpToastLeaving={jumpToastLeaving}
							layersOffsetLeft={detailOpen ? 412 : searchOpen ? 372 : sidebarFull ? 340 : 12}
							polyNoun={polyNoun}
							onSelectVilla={handleSelectVilla}
							onDrillDown={drillDownLevel}
							onMapModeChange={setMapMode}
							onViewerReady={handleViewerReady}
							onMesh3dOnChange={setMesh3dOn}
							onModel3dOnChange={setModel3dOn}
							onModel3dOpacityChange={setModel3dOpacity}
							onProgressColoursChange={setProgressColours}
							onShowLabelsChange={setShowLabels}
							onShowPolygonsChange={setShowPolygons}
						/>
						{/* Top canvas toolbar — level nav + view-mode switcher (SiteToolbar widget). Sibling of
                BuildingViewer so the map transition never pulls it. */}
						<SiteToolbar
							view={view}
							mode={mode}
							level={level}
							activeLevel={activeLevel}
							levels={LEVELS}
							modeTabs={MODE_TABS}
							hasSatellite={hasSatellite}
							hide3d={props.hide3d}
							chromeFade={chromeFade}
							onSelectView={selectView}
							onSelectLevel={selectLevel}
							onSelectMode={selectMode}
						/>

						{/* Active-filter chips — centred under the top toolbar, adding horizontally. Each has an X to remove
                it; the container is click-through (pointer-events-none) so only the chips capture clicks. */}
						{filters.length > 0 && (
							<div
								className={cn(
									"wwc:pointer-events-none wwc:absolute wwc:left-1/2 wwc:top-20 wwc:z-20 wwc:flex wwc:max-w-[70%] wwc:-translate-x-1/2 wwc:flex-wrap wwc:items-center wwc:justify-center wwc:gap-2",
									chromeFade,
								)}
							>
								{filters.map((f) => (
									<span
										key={`${f.kind}:${f.value}`}
										className="wwc:pointer-events-auto wwc:flex wwc:items-center wwc:gap-1.5 wwc:rounded-full wwc:border wwc:border-border wwc:bg-card wwc:py-1 wwc:pl-3 wwc:pr-1.5 wwc:text-xs wwc:font-medium wwc:text-foreground wwc:shadow-md"
									>
										<span className="wwc:text-muted-foreground">{FILTER_KIND_LABEL[f.kind]}:</span>
										{f.label}
										<button
											type="button"
											aria-label={`Remove ${FILTER_KIND_LABEL[f.kind]} ${f.label} filter`}
											onClick={() => setFilters(filters.filter((x) => !(x.kind === f.kind && x.value === f.value)))}
											className="wwc:flex wwc:size-4 wwc:items-center wwc:justify-center wwc:rounded-full wwc:text-muted-foreground wwc:transition-colors wwc:hover:bg-accent wwc:hover:text-foreground"
										>
											<X className="wwc:size-3" />
										</button>
									</span>
								))}
							</div>
						)}

						<ProgressSheet
							capture={capture}
							timeline={TIMELINE_WEEKS}
							selectedWeek={selectedWeek}
							rangeLabel={rangeLabel}
							firstWeek={firstWeek}
							lastWeek={lastWeek}
							reportsOpen={reportsOpen}
							showOnlyProgressionReport={props.showOnlyProgressionReport}
							chromeFade={chromeFade}
							allVillas={ALL_VILLAS}
							progressionData={props.progressionData}
							onCaptureChange={setCapture}
							onReportsOpenChange={setReportsOpen}
							onReportScroll={setReportScrollY}
						/>
					</>
				)}
			</div>

			{/* Blueprints dialog */}
			<Dialog open={blueprintsOpen} onOpenChange={setBlueprintsOpen}>
				<DialogContent className="wwc:max-w-2xl">
					<DialogHeader>
						<DialogTitle>Blueprints — {selected.name}</DialogTitle>
						<DialogDescription>
							{selected.meta} · capture {capture} · {rangeLabel}
						</DialogDescription>
					</DialogHeader>

					<div className="wwc:grid wwc:grid-cols-2 wwc:gap-3">
						{FLOORS.map((f) => (
							<div
								key={f.code}
								className="wwc:flex wwc:flex-col wwc:gap-2 wwc:rounded-lg wwc:border wwc:border-border wwc:p-3"
							>
								<div className="wwc:flex wwc:items-center wwc:justify-between">
									<span className="wwc:text-sm wwc:font-medium">Level {f.code}</span>
									<Badge variant="secondary">{f.value}%</Badge>
								</div>
								<div className="wwc:flex wwc:h-24 wwc:items-center wwc:justify-center wwc:rounded-md wwc:bg-muted wwc:text-xs wwc:text-muted-foreground">
									Sheet A-{f.code}-01
								</div>
							</div>
						))}
					</div>

					<DialogFooter>
						<Button variant="outline" onClick={() => setBlueprintsOpen(false)}>
							Close
						</Button>
						<Button
							onClick={() => {
								props.onOpenBlueprints?.(detailVilla);
								setBlueprintsOpen(false);
							}}
						>
							Open in viewer
						</Button>
					</DialogFooter>
				</DialogContent>
			</Dialog>
		</div>
	);
}
