import type {FileSystemNode} from "../file-system";

// The Core Connect file system — the address space, and nothing else.
//
// Every surface in this workspace already owns its records: WC3_PIPELINES, WC3_PROCESSES,
// WC3_OBJECT_TYPES, WC3_ACTION_TYPES, WC3_PRODUCTS. What none of them had was an ADDRESS. This module
// supplies one, as a reference layer: a folder hierarchy whose leaves point at records that live
// elsewhere. It stores no record data of its own and never will — copying a pipeline's fields in here
// would give the workspace two sources of truth for the same thing, and they would drift within a
// release.
//
// The shape is the FileSystem widget's own `FileSystemNode`: a flat array with `parentId`, each file
// carrying a `ref` the widget treats as opaque and this product reads as {perspectiveId, tabId,
// recordId}.

/**
 * The organizations the top-bar switcher picks between, and the roots of the file system. Defined here
 * because the switcher and the tree must agree on the list: picking an org in the bar shows that org's
 * tree, so two lists would mean a selectable org with no files.
 */
export const WC3_ORGANIZATIONS = [
	"Core Construction",
	"BuildRight Inc",
	"Metro Developers",
	"Nesma United Industries",
] as const;

// ─── The tree ────────────────────────────────────────────────────────────────
//
// Core Construction carries the real tree: every one of the sixteen object types, all three
// pipelines, both processes, five action types and the Capture product, each addressed EXACTLY ONCE.
// One address per record is what keeps the reverse lookup a plain map — a record in two folders has no
// single answer to "where does this live?", which is the question every app listing asks.
//
// The other three organizations carry their own projects and folders, with files that reference
// nothing: a spreadsheet or a write-up is an ordinary thing to keep in a file system, and it lets the
// org switcher visibly change the tree without a record needing two homes.

export const WC3_FS_NODES: FileSystemNode[] = [
	// ── Core Construction ──────────────────────────────────────────────────
	{id: "org-core", name: "Core Construction", kind: "root", parentId: null, updatedAt: "Today", updatedTs: 900},

	{
		id: "prj-falcon",
		name: "Falcon Heights Medical Tower",
		description: "42-storey medical tower in Riyadh. BIM intake, schedule sync and the built-asset ontology live here.",
		kind: "project",
		parentId: "org-core",
		updatedAt: "Tue, Sep 8, 2026, 9:14 AM",
		updatedTs: 890,
		tags: ["healthcare", "riyadh"],
	},
	{
		id: "fld-falcon-pipelines",
		name: "Data pipelines",
		kind: "folder",
		parentId: "prj-falcon",
		updatedAt: "Tue, Sep 8, 2026, 9:14 AM",
		updatedTs: 889,
	},
	{
		id: "f-pipe-bim",
		name: "BIM intake — IFC → WC3 elements",
		kind: "file",
		parentId: "fld-falcon-pipelines",
		updatedAt: "Tue, Sep 8, 2026, 9:14 AM",
		updatedTs: 888,
		fileType: "pipeline",
		ref: {perspectiveId: "pipelines", tabId: "pipelines", recordId: "pipe_bim"},
		tags: ["bim", "ifc"],
	},
	{
		id: "f-pipe-sched",
		name: "P6 schedule sync — XER → activities",
		kind: "file",
		parentId: "fld-falcon-pipelines",
		updatedAt: "Mon, Sep 7, 2026, 4:02 PM",
		updatedTs: 870,
		fileType: "pipeline",
		ref: {perspectiveId: "pipelines", tabId: "pipelines", recordId: "pipe_sched"},
		tags: ["schedule"],
	},
	{
		id: "f-pipe-tel",
		name: "Telemetry & roster — wearables → presence",
		kind: "file",
		parentId: "fld-falcon-pipelines",
		updatedAt: "Mon, Sep 7, 2026, 8:40 AM",
		updatedTs: 860,
		fileType: "pipeline",
		ref: {perspectiveId: "pipelines", tabId: "pipelines", recordId: "pipe_tel"},
		tags: ["telemetry"],
	},
	{
		id: "f-falcon-intake-notes",
		name: "IFC intake — mapping notes",
		kind: "file",
		parentId: "fld-falcon-pipelines",
		updatedAt: "Fri, Sep 4, 2026, 1:20 PM",
		updatedTs: 840,
		fileType: "doc",
	},

	{
		id: "fld-falcon-assets",
		name: "Built assets",
		kind: "folder",
		parentId: "prj-falcon",
		updatedAt: "Mon, Sep 7, 2026, 11:31 AM",
		updatedTs: 865,
	},
	{
		id: "f-ot-project",
		name: "Project",
		kind: "file",
		parentId: "fld-falcon-assets",
		updatedAt: "Mon, Sep 7, 2026, 11:31 AM",
		updatedTs: 864,
		fileType: "object-type",
		ref: {perspectiveId: "ontology", tabId: "object-types", recordId: "ot_project"},
	},
	{
		id: "f-ot-site",
		name: "Site",
		kind: "file",
		parentId: "fld-falcon-assets",
		updatedAt: "Mon, Sep 7, 2026, 11:29 AM",
		updatedTs: 863,
		fileType: "object-type",
		ref: {perspectiveId: "ontology", tabId: "object-types", recordId: "ot_site"},
	},
	{
		id: "f-ot-storey",
		name: "Storey",
		kind: "file",
		parentId: "fld-falcon-assets",
		updatedAt: "Sun, Sep 6, 2026, 5:12 PM",
		updatedTs: 850,
		fileType: "object-type",
		ref: {perspectiveId: "ontology", tabId: "object-types", recordId: "ot_storey"},
	},
	{
		id: "f-ot-element",
		name: "Built Element",
		kind: "file",
		parentId: "fld-falcon-assets",
		updatedAt: "Sun, Sep 6, 2026, 5:10 PM",
		updatedTs: 849,
		fileType: "object-type",
		ref: {perspectiveId: "ontology", tabId: "object-types", recordId: "ot_element"},
	},

	{
		id: "fld-falcon-schedule",
		name: "Schedule",
		kind: "folder",
		parentId: "prj-falcon",
		updatedAt: "Sat, Sep 5, 2026, 10:02 AM",
		updatedTs: 845,
	},
	{
		id: "f-ot-activity",
		name: "Activity",
		kind: "file",
		parentId: "fld-falcon-schedule",
		updatedAt: "Sat, Sep 5, 2026, 10:02 AM",
		updatedTs: 844,
		fileType: "object-type",
		ref: {perspectiveId: "ontology", tabId: "object-types", recordId: "ot_activity"},
	},
	{
		id: "f-at-report-progress",
		name: "Report activity progress",
		kind: "file",
		parentId: "fld-falcon-schedule",
		updatedAt: "Sat, Sep 5, 2026, 9:58 AM",
		updatedTs: 843,
		fileType: "action-type",
		ref: {perspectiveId: "ontology", tabId: "action-types", recordId: "at_report_progress"},
	},
	{
		id: "f-falcon-progress-xlsx",
		name: "Weekly progress rollup",
		kind: "file",
		parentId: "fld-falcon-schedule",
		updatedAt: "Fri, Sep 4, 2026, 6:00 PM",
		updatedTs: 838,
		fileType: "dataset",
	},

	{
		id: "prj-uptown",
		name: "Uptown Tower",
		description: "Commercial tower running the safety and permitting processes end to end.",
		kind: "project",
		parentId: "org-core",
		updatedAt: "Mon, Sep 7, 2026, 2:45 PM",
		updatedTs: 868,
		tags: ["commercial"],
	},
	{
		id: "fld-uptown-safety",
		name: "Safety",
		kind: "folder",
		parentId: "prj-uptown",
		updatedAt: "Mon, Sep 7, 2026, 2:45 PM",
		updatedTs: 867,
	},
	{
		id: "f-proc-obs",
		name: "Observation Manager",
		kind: "file",
		parentId: "fld-uptown-safety",
		updatedAt: "Mon, Sep 7, 2026, 2:45 PM",
		updatedTs: 866,
		fileType: "process",
		ref: {perspectiveId: "processes", tabId: "processes", recordId: "proc_obs"},
		tags: ["hse"],
	},
	{
		id: "f-ot-observation",
		name: "Safety Observation",
		kind: "file",
		parentId: "fld-uptown-safety",
		updatedAt: "Mon, Sep 7, 2026, 2:40 PM",
		updatedTs: 862,
		fileType: "object-type",
		ref: {perspectiveId: "ontology", tabId: "object-types", recordId: "ot_observation"},
	},
	{
		id: "f-at-record-observation",
		name: "Record safety observation",
		kind: "file",
		parentId: "fld-uptown-safety",
		updatedAt: "Mon, Sep 7, 2026, 2:38 PM",
		updatedTs: 861,
		fileType: "action-type",
		ref: {perspectiveId: "ontology", tabId: "action-types", recordId: "at_record_observation"},
	},
	{
		id: "fld-uptown-permitting",
		name: "Permitting",
		kind: "folder",
		parentId: "prj-uptown",
		updatedAt: "Sun, Sep 6, 2026, 8:15 AM",
		updatedTs: 855,
	},
	{
		id: "f-proc-permit",
		name: "Digital Work Permit",
		kind: "file",
		parentId: "fld-uptown-permitting",
		updatedAt: "Sun, Sep 6, 2026, 8:15 AM",
		updatedTs: 854,
		fileType: "process",
		ref: {perspectiveId: "processes", tabId: "processes", recordId: "proc_permit"},
		tags: ["hse", "permits"],
	},
	{
		id: "f-ot-permit",
		name: "Work Permit",
		kind: "file",
		parentId: "fld-uptown-permitting",
		updatedAt: "Sun, Sep 6, 2026, 8:12 AM",
		updatedTs: 853,
		fileType: "object-type",
		ref: {perspectiveId: "ontology", tabId: "object-types", recordId: "ot_permit"},
	},
	{
		id: "f-at-submit-permit",
		name: "Submit permit",
		kind: "file",
		parentId: "fld-uptown-permitting",
		updatedAt: "Sun, Sep 6, 2026, 8:09 AM",
		updatedTs: 852,
		fileType: "action-type",
		ref: {perspectiveId: "ontology", tabId: "action-types", recordId: "at_submit_permit"},
	},

	{
		id: "prj-marina",
		name: "Marina Heights",
		description: "Residential development. Workforce and zone-access records for the site.",
		kind: "project",
		parentId: "org-core",
		updatedAt: "Fri, Sep 4, 2026, 3:22 PM",
		updatedTs: 836,
		tags: ["residential"],
	},
	{
		id: "fld-marina-workforce",
		name: "Workforce",
		kind: "folder",
		parentId: "prj-marina",
		updatedAt: "Fri, Sep 4, 2026, 3:22 PM",
		updatedTs: 835,
	},
	{
		id: "f-ot-worker",
		name: "Worker",
		kind: "file",
		parentId: "fld-marina-workforce",
		updatedAt: "Fri, Sep 4, 2026, 3:22 PM",
		updatedTs: 834,
		fileType: "object-type",
		ref: {perspectiveId: "ontology", tabId: "object-types", recordId: "ot_worker"},
	},
	{
		id: "f-ot-crew",
		name: "Crew",
		kind: "file",
		parentId: "fld-marina-workforce",
		updatedAt: "Fri, Sep 4, 2026, 3:20 PM",
		updatedTs: 833,
		fileType: "object-type",
		ref: {perspectiveId: "ontology", tabId: "object-types", recordId: "ot_crew"},
	},
	{
		id: "f-ot-cert",
		name: "Certification",
		kind: "file",
		parentId: "fld-marina-workforce",
		updatedAt: "Fri, Sep 4, 2026, 3:18 PM",
		updatedTs: 832,
		fileType: "object-type",
		ref: {perspectiveId: "ontology", tabId: "object-types", recordId: "ot_cert"},
	},
	{
		id: "f-at-assign-crew",
		name: "Assign crew to activity",
		kind: "file",
		parentId: "fld-marina-workforce",
		updatedAt: "Thu, Sep 3, 2026, 11:40 AM",
		updatedTs: 828,
		fileType: "action-type",
		ref: {perspectiveId: "ontology", tabId: "action-types", recordId: "at_assign_crew"},
	},
	{
		id: "fld-marina-access",
		name: "Access control",
		kind: "folder",
		parentId: "prj-marina",
		updatedAt: "Thu, Sep 3, 2026, 9:05 AM",
		updatedTs: 826,
	},
	{
		id: "f-ot-zone",
		name: "Zone",
		kind: "file",
		parentId: "fld-marina-access",
		updatedAt: "Thu, Sep 3, 2026, 9:05 AM",
		updatedTs: 825,
		fileType: "object-type",
		ref: {perspectiveId: "ontology", tabId: "object-types", recordId: "ot_zone"},
	},
	{
		id: "f-ot-access-grant",
		name: "Access Grant",
		kind: "file",
		parentId: "fld-marina-access",
		updatedAt: "Thu, Sep 3, 2026, 9:02 AM",
		updatedTs: 824,
		fileType: "object-type",
		ref: {perspectiveId: "ontology", tabId: "object-types", recordId: "ot_access_grant"},
	},
	{
		id: "f-at-grant-access",
		name: "Grant zone access",
		kind: "file",
		parentId: "fld-marina-access",
		updatedAt: "Wed, Sep 2, 2026, 4:44 PM",
		updatedTs: 820,
		fileType: "action-type",
		ref: {perspectiveId: "ontology", tabId: "action-types", recordId: "at_grant_access"},
	},

	{
		id: "prj-neom",
		name: "NEOM Site 4",
		description:
			"Infrastructure package. Equipment, sensors and logistics, plus the platform products installed on it.",
		kind: "project",
		parentId: "org-core",
		updatedAt: "Wed, Sep 2, 2026, 7:30 AM",
		updatedTs: 818,
		tags: ["infrastructure", "neom"],
	},
	{
		id: "fld-neom-equipment",
		name: "Equipment & sensors",
		kind: "folder",
		parentId: "prj-neom",
		updatedAt: "Wed, Sep 2, 2026, 7:30 AM",
		updatedTs: 817,
	},
	{
		id: "f-ot-equipment",
		name: "Equipment",
		kind: "file",
		parentId: "fld-neom-equipment",
		updatedAt: "Wed, Sep 2, 2026, 7:30 AM",
		updatedTs: 816,
		fileType: "object-type",
		ref: {perspectiveId: "ontology", tabId: "object-types", recordId: "ot_equipment"},
	},
	{
		id: "f-ot-sensor",
		name: "Sensor",
		kind: "file",
		parentId: "fld-neom-equipment",
		updatedAt: "Wed, Sep 2, 2026, 7:28 AM",
		updatedTs: 815,
		fileType: "object-type",
		ref: {perspectiveId: "ontology", tabId: "object-types", recordId: "ot_sensor"},
	},
	{
		id: "f-at-retire-equipment",
		name: "Retire equipment",
		kind: "file",
		parentId: "fld-neom-equipment",
		updatedAt: "Tue, Sep 1, 2026, 2:10 PM",
		updatedTs: 810,
		fileType: "action-type",
		ref: {perspectiveId: "ontology", tabId: "action-types", recordId: "at_retire_equipment"},
	},
	{
		id: "f-at-reassign-sensor",
		name: "Reassign sensor to worker",
		kind: "file",
		parentId: "fld-neom-equipment",
		updatedAt: "Tue, Sep 1, 2026, 2:07 PM",
		updatedTs: 809,
		fileType: "action-type",
		ref: {perspectiveId: "ontology", tabId: "action-types", recordId: "at_reassign_sensor"},
	},
	{
		id: "fld-neom-logistics",
		name: "Logistics",
		kind: "folder",
		parentId: "prj-neom",
		updatedAt: "Mon, Aug 31, 2026, 6:41 PM",
		updatedTs: 800,
	},
	{
		id: "f-ot-delivery",
		name: "Material Delivery",
		kind: "file",
		parentId: "fld-neom-logistics",
		updatedAt: "Mon, Aug 31, 2026, 6:41 PM",
		updatedTs: 799,
		fileType: "object-type",
		ref: {perspectiveId: "ontology", tabId: "object-types", recordId: "ot_delivery"},
	},
	{
		id: "fld-neom-platform",
		name: "Platform",
		kind: "folder",
		parentId: "prj-neom",
		updatedAt: "Mon, Aug 31, 2026, 11:02 AM",
		updatedTs: 795,
	},
	{
		id: "f-prod-capture",
		name: "Capture",
		kind: "file",
		parentId: "fld-neom-platform",
		updatedAt: "Mon, Aug 31, 2026, 11:02 AM",
		updatedTs: 794,
		fileType: "product",
		ref: {perspectiveId: "products", tabId: "catalogue", recordId: "capture"},
		tags: ["ontology-product"],
	},
	{
		id: "f-ot-lint-demo",
		name: "Lint Demo: Badge Events Raw Table",
		kind: "file",
		parentId: "fld-neom-platform",
		updatedAt: "Sun, Aug 30, 2026, 4:15 PM",
		updatedTs: 790,
		fileType: "object-type",
		ref: {perspectiveId: "ontology", tabId: "object-types", recordId: "ot_lint_demo"},
		tags: ["needs-review"],
	},
	{
		id: "f-neom-decommission",
		name: "Sensor decommission plan (superseded)",
		kind: "file",
		parentId: "fld-neom-equipment",
		updatedAt: "Thu, Aug 27, 2026, 10:00 AM",
		updatedTs: 770,
		fileType: "doc",
		trashed: true,
	},

	// ── BuildRight Inc ────────────────────────────────────────────────────────
	{id: "org-buildright", name: "BuildRight Inc", kind: "root", parentId: null, updatedAt: "Today", updatedTs: 700},
	{
		id: "prj-harbor",
		name: "Harbor Bridge",
		description: "Mainland-to-port crossing. Survey readings and handover records.",
		kind: "project",
		parentId: "org-buildright",
		updatedAt: "Mon, Sep 7, 2026, 9:00 AM",
		updatedTs: 699,
		tags: ["infrastructure"],
	},
	{
		id: "fld-harbor-survey",
		name: "Survey",
		kind: "folder",
		parentId: "prj-harbor",
		updatedAt: "Mon, Sep 7, 2026, 9:00 AM",
		updatedTs: 698,
	},
	{
		id: "f-harbor-spans",
		name: "Span deflection readings",
		kind: "file",
		parentId: "fld-harbor-survey",
		updatedAt: "Mon, Sep 7, 2026, 9:00 AM",
		updatedTs: 697,
		fileType: "dataset",
	},
	{
		id: "f-harbor-method",
		name: "Deck pour method statement",
		kind: "file",
		parentId: "fld-harbor-survey",
		updatedAt: "Fri, Sep 4, 2026, 5:30 PM",
		updatedTs: 690,
		fileType: "doc",
	},
	{
		id: "fld-harbor-handover",
		name: "Handover",
		kind: "folder",
		parentId: "prj-harbor",
		updatedAt: "Wed, Sep 2, 2026, 12:00 PM",
		updatedTs: 685,
	},
	{
		id: "f-harbor-asbuilt",
		name: "As-built register",
		kind: "file",
		parentId: "fld-harbor-handover",
		updatedAt: "Wed, Sep 2, 2026, 12:00 PM",
		updatedTs: 684,
		fileType: "dataset",
	},

	// ── Metro Developers ──────────────────────────────────────────────────────
	{id: "org-metro", name: "Metro Developers", kind: "root", parentId: null, updatedAt: "Today", updatedTs: 600},
	{
		id: "prj-techpark",
		name: "Tech Park Campus",
		description: "Sustainable office campus, currently in fit-out.",
		kind: "project",
		parentId: "org-metro",
		updatedAt: "Sun, Sep 6, 2026, 1:15 PM",
		updatedTs: 599,
		tags: ["commercial"],
	},
	{
		id: "fld-techpark-fitout",
		name: "Fit-out",
		kind: "folder",
		parentId: "prj-techpark",
		updatedAt: "Sun, Sep 6, 2026, 1:15 PM",
		updatedTs: 598,
	},
	{
		id: "f-techpark-packages",
		name: "Fit-out packages",
		kind: "file",
		parentId: "fld-techpark-fitout",
		updatedAt: "Sun, Sep 6, 2026, 1:15 PM",
		updatedTs: 597,
		fileType: "dataset",
	},
	{
		id: "f-techpark-brief",
		name: "Sustainability brief",
		kind: "file",
		parentId: "fld-techpark-fitout",
		updatedAt: "Thu, Sep 3, 2026, 8:45 AM",
		updatedTs: 590,
		fileType: "doc",
	},
	{
		id: "f-techpark-shared-bim",
		name: "Shared BIM coordination log",
		kind: "file",
		parentId: "fld-techpark-fitout",
		updatedAt: "Wed, Sep 2, 2026, 10:30 AM",
		updatedTs: 585,
		fileType: "dataset",
	},

	// ── Nesma United Industries ───────────────────────────────────────────────
	{
		id: "org-nesma",
		name: "Nesma United Industries",
		kind: "root",
		parentId: null,
		updatedAt: "Today",
		updatedTs: 500,
	},
	{
		id: "prj-jafurah",
		name: "Jafurah Phase 2",
		description: "Energy package in mobilisation.",
		kind: "project",
		parentId: "org-nesma",
		updatedAt: "Fri, Sep 4, 2026, 7:00 AM",
		updatedTs: 499,
		tags: ["energy"],
	},
	{
		id: "fld-jafurah-mobilisation",
		name: "Mobilisation",
		kind: "folder",
		parentId: "prj-jafurah",
		updatedAt: "Fri, Sep 4, 2026, 7:00 AM",
		updatedTs: 498,
	},
	{
		id: "f-jafurah-manpower",
		name: "Manpower histogram",
		kind: "file",
		parentId: "fld-jafurah-mobilisation",
		updatedAt: "Fri, Sep 4, 2026, 7:00 AM",
		updatedTs: 497,
		fileType: "dataset",
	},
	{
		id: "f-jafurah-camp",
		name: "Camp readiness checklist",
		kind: "file",
		parentId: "fld-jafurah-mobilisation",
		updatedAt: "Tue, Sep 1, 2026, 6:20 PM",
		updatedTs: 490,
		fileType: "doc",
	},
];
