// Builds standalone/src/fonts.css with the webfonts inlined as data: URIs.
//
// packages/tokens/src/fonts.css pulls Figtree + IBM Plex Mono from Google Fonts over the network. A
// file meant to be emailed around has to render correctly with no network at all, so this fetches the
// woff2 files once and base64-embeds them. Re-run only when the font stack changes.
import {writeFileSync} from "node:fs";

const FAMILIES = [
	"Figtree:ital,wght@0,300..900;1,300..900",
	"IBM+Plex+Mono:ital,wght@0,400;0,500;0,600;1,400",
];

// Ask as a modern browser or Google serves legacy formats instead of woff2.
const UA =
	"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const url = `https://fonts.googleapis.com/css2?family=${FAMILIES.join("&family=")}&display=swap`;
const css = await fetch(url, {headers: {"User-Agent": UA}}).then((r) => {
	if (!r.ok) throw new Error(`Google Fonts responded ${r.status}`);
	return r.text();
});

const refs = [...new Set([...css.matchAll(/url\((https:\/\/[^)]+\.woff2)\)/g)].map((m) => m[1]))];
console.log(`${refs.length} woff2 files referenced`);

const cache = new Map();
for (const ref of refs) {
	const buf = Buffer.from(await fetch(ref).then((r) => r.arrayBuffer()));
	cache.set(ref, `data:font/woff2;base64,${buf.toString("base64")}`);
	process.stdout.write(".");
}
process.stdout.write("\n");

const inlined = css.replace(/url\((https:\/\/[^)]+\.woff2)\)/g, (m, u) => `url(${cache.get(u) ?? u})`);
const bytes = Buffer.byteLength(inlined);

writeFileSync(
	new URL("./src/fonts.css", import.meta.url),
	`/* Generated by standalone/build-fonts.mjs — do not edit. Figtree + IBM Plex Mono, base64-embedded\n   so a standalone HTML renders with the right type offline. */\n${inlined}`,
);
console.log(`wrote standalone/src/fonts.css (${(bytes / 1024).toFixed(0)} KB)`);
