import {randomUUID} from "node:crypto";
// Workspace materializer + recent-workspaces store (Phase 3/4). On Edit, Studio writes a real, external
// workspace — src/ + .core/ + a cross-editor AGENTS.md — then never reads it back. The workspace is a
// one-way handoff: the external editor owns src/; .core/ is canonical Core CONTEXT FOR THE EDITOR
// (a seed + validation target, not live truth). There is no session, no history, no agent here. Each
// editor's own config is projected from .core/ by Editor.prepare() (see editors.ts), not written here.
//
// The recent-workspaces store records path + editor + timestamps for REOPENING/RELAUNCHING ONLY — it never
// renders workspace changes (that is what governance forbids).
import {existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync} from "node:fs";
import {homedir} from "node:os";
import {join} from "node:path";

import {getSdk} from "./canonical";
import {seedFor} from "./seeds";

// The workspace envelope schema. Bump when the .core/ layout changes so editors/tooling can migrate.
const WORKSPACE_SCHEMA_VERSION = "core-workspace/0.1";

// Same policy as CLAUDE.md, cross-editor convention (Codex/others read AGENTS.md). Editor-agnostic, so the
// materializer owns it; editor-SPECIFIC config (CLAUDE.md, .mcp.json, .cursor/rules…) is Editor.prepare()'s.
const AGENTS_MD = `# Core workspace — agent policy

Core is the source of truth; reuse before you build. Edit \`src/page.tsx\` (keep its default \`Page\`
export). Read \`.core/\` for context (advisory seed + validation target — never hand-edit it). Use the
\`core\` MCP (resolve_template → resolve_widgets → validate_page) before adding UI. Import artifacts from
\`@corensystem/core-ui/<kebab-name>\`. Only write custom code when Core has nothing suitable, and say so.
`;

export type WorkspaceMeta = {
	id: string;
	name: string;
	path: string;
	template: {id: string; version: string};
	created: string;
};

function writeJson(path: string, value: unknown): void {
	writeFileSync(path, JSON.stringify(value, null, 2) + "\n", "utf8");
}

// Materialize a workspace at `location` from a canonical template. Writes once; Studio never reads it back.
// Throws if the template has no canonical seed, or if `location` already exists and is non-empty (we never
// clobber a user's folder). Editor-specific config is added afterward by Editor.prepare().
export function materializeWorkspace(opts: {templateId: string; location: string; name?: string}): WorkspaceMeta {
	const {templateId, location} = opts;

	const seed = seedFor(templateId);
	if (!seed) throw new Error(`"${templateId}" isn't wired to a canonical seed yet.`);
	if (existsSync(location) && readdirSync(location).length > 0)
		throw new Error(`"${location}" already exists and is not empty.`);

	const sdk = getSdk();
	const manifest = sdk.loadManifest({id: templateId, tier: "template"});
	const name = opts.name ?? manifest.name ?? templateId;
	const version = manifest.version ?? "1.0.0";
	const id = randomUUID();
	const created = new Date().toISOString();

	// The composition seed + validation target — canonical Core output, generated by the SDK.
	const {page} = sdk.generatePageInstance({template: {id: templateId}, fill: "recommended", name: `${name} page`});

	// --- write the editor-agnostic core (mkdir -p; src/ + .core/) ---------------------------------
	mkdirSync(join(location, "src"), {recursive: true});
	mkdirSync(join(location, ".core"), {recursive: true});

	// src/ — the editable app source the editor owns.
	writeFileSync(join(location, "src", "page.tsx"), seed.source, "utf8");

	// .core/ — canonical, editor-agnostic Core context.
	writeJson(join(location, ".core", "workspace.json"), {
		schemaVersion: WORKSPACE_SCHEMA_VERSION,
		id,
		name,
		template: {id: templateId, version},
		created,
	});
	writeJson(join(location, ".core", "template.json"), manifest);
	writeJson(join(location, ".core", "page-instance.json"), page);

	// Cross-editor policy file (editor-specific config is Editor.prepare()'s job).
	writeFileSync(join(location, "AGENTS.md"), AGENTS_MD, "utf8");

	return {id, name, path: location, template: {id: templateId, version}, created};
}

// --- Recent-workspaces store (reopen/relaunch only — never a preview of workspace content) --------------

const STORE_DIR = join(homedir(), ".core-studio");
const RECENT_FILE = join(STORE_DIR, "recent-workspaces.json");
const RECENT_CAP = 50;

export type RecentEntry = {
	id: string;
	name: string;
	template: {id: string; version: string};
	path: string;
	editor: string;
	created: string;
	lastOpened: string;
};

function readRecent(): RecentEntry[] {
	try {
		const arr = JSON.parse(readFileSync(RECENT_FILE, "utf8"));
		return Array.isArray(arr) ? arr : [];
	} catch {
		return [];
	}
}

function saveRecent(entries: RecentEntry[]): void {
	mkdirSync(STORE_DIR, {recursive: true});
	writeJson(RECENT_FILE, entries.slice(0, RECENT_CAP));
}

// Prepend/dedupe by path so the most recently touched workspace is first.
export function addRecent(entry: RecentEntry): void {
	const rest = readRecent().filter((e) => e.path !== entry.path);
	saveRecent([entry, ...rest]);
}

// Bump lastOpened (and editor) for an existing entry on relaunch.
export function touchRecent(path: string, editor?: string): void {
	const now = new Date().toISOString();
	const entries = readRecent();
	const hit = entries.find((e) => e.path === path);
	if (!hit) return;
	hit.lastOpened = now;
	if (editor) hit.editor = editor;
	saveRecent([hit, ...entries.filter((e) => e.path !== path)]);
}

// The current git branch of a workspace, read from .git/HEAD (metadata only — never file contents). Null
// when the folder isn't a git repo or is in a detached state.
function gitBranch(path: string): string | null {
	try {
		const head = readFileSync(join(path, ".git", "HEAD"), "utf8").trim();
		const m = head.match(/^ref:\s*refs\/heads\/(.+)$/);
		return m ? m[1] : null;
	} catch {
		return null;
	}
}

// List recent workspaces with cheap filesystem METADATA (existence + src mtime + git branch) — never their
// contents. This is for reopen/relaunch and light status only; it does not reflect workspace edits.
export function listRecent(): Array<
	RecentEntry & {exists: boolean; lastModified: string | null; branch: string | null}
> {
	return readRecent().map((e) => {
		let exists = false;
		let lastModified: string | null = null;
		try {
			lastModified = statSync(join(e.path, "src")).mtime.toISOString();
			exists = true;
		} catch {
			// Folder was moved/deleted — keep the entry (reopen will fail gracefully) but mark it missing.
		}
		return {...e, exists, lastModified, branch: exists ? gitBranch(e.path) : null};
	});
}
