#!/usr/bin/env node
/**
 * Vendors the Core typefaces into the repo as self-hosted WOFF2, and regenerates
 * packages/tokens/src/fonts.css to point at them.
 *
 * The declared typography used to be an `@import` from the Google Fonts CDN, which made it a RUNTIME
 * dependency on a third-party host: an offline, air-gapped or CSP-restricted build silently fell back
 * to a system stack while still looking token-compliant. Shipping the files removes that.
 *
 * Run after changing which families or weights the tokens declare:
 *
 *   node scripts/vendor-fonts.mjs
 *
 * Only latin and latin-ext subsets are kept — other subsets would multiply the payload for scripts the
 * product does not use, and degrade to the fallback stack.
 */

import {mkdirSync, rmSync, writeFileSync} from "node:fs";
import {dirname, join} from "node:path";
import {fileURLToPath} from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const fontsDir = join(repoRoot, "packages/tokens/src/fonts");
const cssPath = join(repoRoot, "packages/tokens/src/fonts.css");

// A modern UA is required: Google Fonts serves TTF to anything it does not recognise as woff2-capable.
const UA =
	"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

/** Families and axes, mirroring --font-sans / --font-mono / --font-serif in theme.css. */
const QUERY = [
	"family=Figtree:ital,wght@0,300..900;1,300..900",
	"family=IBM+Plex+Mono:ital,wght@0,400;0,500;0,600;1,400",
	"family=Lora:ital,wght@0,400..700;1,400..700",
].join("&");

const FAMILY_ORDER = {Figtree: 0, "IBM Plex Mono": 1, Lora: 2};

/** Which subset a unicode-range belongs to, or null for one we deliberately skip. */
function subsetOf(unicodeRange) {
	if (unicodeRange.includes("U+0100-02BA")) return "latin-ext";
	if (unicodeRange.includes("U+0000-00FF")) return "latin";
	return null;
}

async function main() {
	const res = await fetch(`https://fonts.googleapis.com/css2?${QUERY}&display=swap`, {headers: {"User-Agent": UA}});
	if (!res.ok) throw new Error(`Google Fonts responded ${res.status}`);
	const css = await res.text();

	const faces = [];
	for (const [, block] of css.matchAll(/@font-face\s*\{(.*?)\}/gs)) {
		const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
		const style = block.match(/font-style:\s*(\w+)/)?.[1];
		const weight = block.match(/font-weight:\s*([^;]+);/)?.[1]?.trim();
		const unicodeRange = block.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
		const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
		if (!family || !style || !weight || !unicodeRange || !url) continue;
		const subset = subsetOf(unicodeRange);
		if (!subset) continue;
		const slug = family.toLowerCase().replaceAll(" ", "-");
		faces.push({family, style, weight, unicodeRange, url, file: `${slug}-${style}-${weight.replaceAll(" ", "-")}-${subset}.woff2`});
	}
	if (faces.length === 0) throw new Error("No woff2 faces parsed — the Google Fonts response shape may have changed");

	rmSync(fontsDir, {recursive: true, force: true});
	mkdirSync(fontsDir, {recursive: true});
	const written = new Set();
	for (const face of faces) {
		if (written.has(face.file)) continue;
		written.add(face.file);
		const bin = await fetch(face.url, {headers: {"User-Agent": UA}});
		if (!bin.ok) throw new Error(`Failed to download ${face.file}: ${bin.status}`);
		writeFileSync(join(fontsDir, face.file), Buffer.from(await bin.arrayBuffer()));
	}

	faces.sort(
		(a, b) =>
			(FAMILY_ORDER[a.family] ?? 9) - (FAMILY_ORDER[b.family] ?? 9) ||
			a.style.localeCompare(b.style) ||
			a.weight.localeCompare(b.weight) ||
			a.unicodeRange.localeCompare(b.unicodeRange),
	);

	const header = `/* Self-hosted Core typefaces.
 *
 * These used to be an @import from the Google Fonts CDN. That made the declared typography a RUNTIME
 * dependency on a third-party host: offline builds, air-gapped installs and CSP-restricted apps
 * silently fell back to a system stack while still looking token-compliant. The WOFF2 files now ship
 * inside @corensystem/core-tokens, so \`--font-sans\` / \`--font-serif\` / \`--font-mono\` resolve to the same
 * computed family everywhere, with no external request.
 *
 * Figtree and Lora are variable fonts (one file spans the whole weight range); IBM Plex Mono ships a
 * file per weight. Latin and latin-ext subsets only — other subsets are deliberately omitted to keep
 * the package small, and degrade to the fallback stack.
 *
 * All three families are SIL Open Font License 1.1 — see ./fonts/LICENSE.md.
 *
 * GENERATED by scripts/vendor-fonts.mjs — do not edit by hand.
 */
`;
	const blocks = faces.map(
		(f) =>
			`@font-face {\n\tfont-family: "${f.family}";\n\tfont-style: ${f.style};\n\tfont-weight: ${f.weight};\n\tfont-display: swap;\n\tsrc: url("./fonts/${f.file}") format("woff2");\n\tunicode-range: ${f.unicodeRange};\n}`,
	);
	writeFileSync(cssPath, `${header}\n${blocks.join("\n\n")}\n`);
	console.log(`[vendor-fonts] ${written.size} woff2 file(s), ${faces.length} @font-face rule(s) → packages/tokens/src/fonts.css`);
}

main().catch((error) => {
	console.error(`[vendor-fonts] ${error.message}`);
	process.exit(1);
});
